Dev
aonexe/BusinessProcessPetProject pull request #8
Opened 2023-02-03 09:21 UTC by aonexe

2023-02-03 10:42 UTC, Michael2281337 requested changes
Хорошо, к миграциям предлагаю присмотреться внимательнее, по остальному - слегка докопался до всяких мелочей

2023-02-03 10:42 UTC, Michael2281337 commented on src/main/java/com/vorsin/businessProcess/controllers/StageRelationController.java
> +@RequestMapping("/stage-relations")
stage-relation в ед. числе

2023-02-03 10:42 UTC, Michael2281337 commented on src/main/java/com/vorsin/businessProcess/controllers/StageRelationController.java
> +    public ResponseEntity<HttpStatus> createStage(@RequestBody @Valid StageRelationRequest stageRelationRequest) {
createStage или createStageRelation?

2023-02-03 10:42 UTC, Michael2281337 commented on src/main/java/com/vorsin/businessProcess/dto/StageResponse.java
> +//    private List<StageRelation> stageRelations;
Там, где комментишь код удобно добавлять TODO, что бы не потерять контекст. Со временем может накопиться много таких комментариев

2023-02-03 10:42 UTC, Michael2281337 commented on src/main/java/com/vorsin/businessProcess/models/Stage.java
> +//    @OneToMany(mappedBy = "toStage", fetch = FetchType.LAZY)
предлагаю к todo добавить описание

2023-02-03 10:42 UTC, Michael2281337 commented on src/main/java/com/vorsin/businessProcess/services/StageRelationService.java
> +    private void checkIfStagesExists(int fromStageId, int toStageId) {
Предлагаю сделать метод чуть более универсальным и принимать тут лист стейджей, а не два. Возможно, в дальнейшем мы вынесем этот метод в Util и будем использовать не только для проверки 2х стеджей для релейшена

2023-02-03 10:42 UTC, Michael2281337 commented on src/main/java/com/vorsin/businessProcess/services/StageRelationService.java
> +                (generateTitle(stageRelationRequest.getFromStageId(), stageRelationRequest.getToStageId()));
Не техническое предложение, а скорее как фича - предлагаю дать возможность пользователю задавать кастомный тайтл, и если он не задан - генерить его

2023-02-03 10:42 UTC, Michael2281337 commented on src/main/java/com/vorsin/businessProcess/services/StageRelationService.java
> +    private void initStage(StageRelation stageRelation, StageRelationRequest stageRelationRequest) {
Предлагаю передавать только айди из реквеста. Когда начнешь писать тесты - поймешь, почему небольшие дто лучше всего разворачивать

2023-02-03 10:42 UTC, Michael2281337 commented on src/main/java/com/vorsin/businessProcess/services/StageRelationService.java
> +    private void initStage(StageRelation stageRelation, StageRelationRequest stageRelationRequest) {
И тут инит не стейджа, а релейшена :)
И, судя по логике, это даже не инит)

2023-02-03 10:42 UTC, Michael2281337 commented on src/main/java/com/vorsin/businessProcess/services/StageRelationService.java
> +                (generateTitle(stageRelationRequest.getFromStageId(), stageRelationRequest.getToStageId()));
Предлагаю дать возможность пользователю создавать кастомный тайтл как опциональное поле. Ниже немного подробнее расписал

2023-02-03 10:42 UTC, Michael2281337 commented on src/main/java/com/vorsin/businessProcess/services/StageRelationService.java
> +    private void initNewStageRelation(StageRelation stageRelation, StageRelationRequest stageRelationRequest) {
Предлагаю развернуть реквест и передавать айдишники из него. Для тестов будет удобнее

2023-02-03 10:42 UTC, Michael2281337 commented on src/main/java/com/vorsin/businessProcess/services/StageRelationService.java
> +    private StageRelationResponse convertToStageRelationResponse(StageRelation stageRelation) {
Нам точно для этого нужен отдельный метод в одну строчку?)

2023-02-03 10:42 UTC, Michael2281337 commented on src/main/java/com/vorsin/businessProcess/services/StageRelationService.java
> +            initStage(stageRelation.get(), stageRelationRequest);
Название метода точно инит стейдж?)

2023-02-03 10:42 UTC, Michael2281337 commented on src/main/java/com/vorsin/businessProcess/services/StageService.java
> +            initStage(stage.get(), stageRequest.getBusinessProcessId(), stageRequest.getTitle());
Точно инит метод должен называться?)

2023-02-03 10:42 UTC, Michael2281337 commented on src/main/java/com/vorsin/businessProcess/services/StageService.java
> -    private void initStage(Stage stage, StageRequest stageRequest) {
Тут тоже предлагаю развернуть стейдж реквест на составляющие. Для тестов будет удобнее потом

2023-02-03 10:42 UTC, Michael2281337 commented on src/main/resources/db/migration/V1__init_database.sql
> +CREATE TABLE stage
Погоди, ты тут миграцию редактируешь?) Так нельзя :) Нужно создать V2 миграцию и там делать ALTER TABLE и прочие изменения. Если ты сейчас запустишь это на не пустой базе, то у тебя миграция упадет

2023-02-03 11:00 UTC, aonexe commented on src/main/java/com/vorsin/businessProcess/controllers/StageRelationController.java
> +@RequestMapping("/stage-relations")
исправлено на stages-relations

2023-02-03 11:04 UTC, aonexe commented on src/main/java/com/vorsin/businessProcess/controllers/StageRelationController.java
> +    public ResponseEntity<HttpStatus> createStage(@RequestBody @Valid StageRelationRequest stageRelationRequest) {
исправлено на createStageRelation

также исправлено: 
updateStageRelation
deleteStageRelation
getStagesRelations

2023-02-03 11:05 UTC, aonexe commented on src/main/java/com/vorsin/businessProcess/dto/StageResponse.java
> +//    private List<StageRelation> stageRelations;
добавил todo
апдейт сегодня вечером

2023-02-03 11:06 UTC, aonexe commented on src/main/java/com/vorsin/businessProcess/models/Stage.java
> +//    @OneToMany(mappedBy = "toStage", fetch = FetchType.LAZY)
добавил todo
апдейт сегодня вечером

2023-02-03 14:04 UTC, aonexe commented on src/main/java/com/vorsin/businessProcess/services/StageRelationService.java
> +    private void checkIfStagesExists(int fromStageId, int toStageId) {
Предлагаю принимать лист с Integer с id

2023-02-03 19:08 UTC, aonexe commented on src/main/java/com/vorsin/businessProcess/services/StageRelationService.java
> +            initStage(stageRelation.get(), stageRelationRequest);
исправлено на modifyStageRelation

2023-02-03 19:22 UTC, aonexe commented on src/main/java/com/vorsin/businessProcess/services/StageRelationService.java
> +    private StageRelationResponse convertToStageRelationResponse(StageRelation stageRelation) {
убрано для всех сервисов

2023-02-03 19:23 UTC, aonexe commented on src/main/java/com/vorsin/businessProcess/services/StageService.java
> +            initStage(stage.get(), stageRequest.getBusinessProcessId(), stageRequest.getTitle());
исправлено на modifyStage

2023-02-03 19:23 UTC, aonexe commented on src/main/resources/db/migration/V1__init_database.sql
> +CREATE TABLE stage
последний раз, честно, больше не буду!!!

2023-02-04 16:22 UTC, aonexe commented on src/main/java/com/vorsin/businessProcess/services/StageRelationService.java
> +    private void initNewStageRelation(StageRelation stageRelation, StageRelationRequest stageRelationRequest) {
развернул для всех сервисов

2023-02-05 16:23 UTC, Michael2281337 commented on src/main/java/com/vorsin/businessProcess/services/BPService.java
> +        if (bpRequest.getTitle().trim().equals("")) {
isEmpty() or isBlank()

2023-02-05 16:23 UTC, Michael2281337 commented on src/main/resources/db/migration/V1__init_database.sql
>  );
add new line at the end of the file :)

2023-02-05 19:07 UTC, merged